# Copyright (c) 2016 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Shotgun Desktop when it
# is running in its project level configuration

includes:
- ../common/frameworks.yml
- ../common/engines.yml
- ../common/apps.yml
- ../common/settings/tk-multi-publish2.yml

desktop.project:
  apps:

    tk-multi-pythonconsole: '@common.apps.tk-multi-pythonconsole'

    tk-multi-publish2:
      help_url: "@common.apps.tk-multi-publish2.help_url"
      collector: "{self}/collector.py"
      publish_plugins:
        - '@common.settings.tk-multi-publish2.publish_file'
        - '@common.settings.tk-multi-publish2.upload_version'
      location: "@common.apps.tk-multi-publish2.location"

    tk-multi-launchapp:
      use_software_entity: true
      hook_before_register_command: "{config}/tk-multi-launchapp/before_register_command.py"
      location: "@common.apps.tk-multi-launchapp.location"

  collapse_rules:
  - {button_label: $app, match: Launch $app, menu_label: None}
  default_group: Studio
  groups:
  - matches:
    - '*Fla*'
    - '*Houdini*'
    - '*Mari*'
    - '*Max*'
    - '*Maya*'
    - '*Motion*'
    - '*Nuke*'
    - '*Photoshop*'
    - 'CC*'
    - '*Softimage*'
    name: Creative Tools
  - matches:
    - '*Hiero*'
    name: Editorial Tools
  location: "@common.engines.tk-desktop.location"
