# Copyright (c) 2016 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Photoshop Integration when it
# is running in its project level configuration

includes:
- ../common/engines.yml
- ../common/apps.yml
- apps.yml

photoshopcc.site:
  apps:
    tk-multi-about: '@common.apps.tk-multi-about'

    tk-multi-pythonconsole: '@common.apps.tk-multi-pythonconsole'

    tk-multi-loader2:
      action_mappings:
        Photoshop Image: [add_as_a_layer, open_file]
        Rendered Image: [add_as_a_layer, open_file]
        Image: [add_as_a_layer, open_file]
        Texture: [add_as_a_layer, open_file]
      actions_hook: '{self}/tk-photoshopcc_actions.py'
      entities:
      - caption: Project
        type: Hierarchy
        root:
        publish_filters: []
      - caption: My Tasks
        type: Query
        entity_type: Task
        filters:
        - [task_assignees, is, '{context.user}']
        hierarchy: [project, entity, content]
      # ignore publishes without a status. with zero config, it is very easy
      # to publish the same path multiple times. the default zero config publish
      # plugins will clear the status of previous publishes of the same path.
      # this filter means only the latest publish will be displayed.
      publish_filters: [["sg_status_list", "is_not", null]]
      location: "@common.apps.tk-multi-loader2.location"

    tk-multi-shotgunpanel: '@photoshopcc.apps.tk-multi-shotgunpanel'

  shelf_favorites: []
  debug_logging: true
  location: "@common.engines.tk-photoshopcc.location"
  automatic_context_switch: false
