# Copyright (c) 2016 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Maya Integration when it
# is running in its project level configuration

includes:
- ../common/engines.yml
- ../common/apps.yml
- apps.yml

maya.asset_step:
  apps:
    tk-multi-about: '@common.apps.tk-multi-about'
    
    tk-multi-workfiles2: '@maya.apps.tk-multi-workfiles2.asset_step'

    tk-multi-publish2: '@maya.apps.tk-multi-publish2'

    tk-multi-loader2: '@maya.apps.tk-multi-loader2'

    tk-multi-shotgunpanel: '@maya.apps.tk-multi-shotgunpanel'
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  template_project: asset_work_area_maya
  automatic_context_switch: false
  location: "@common.engines.tk-maya.location"

maya.project:
  apps:
    tk-multi-about: '@common.apps.tk-multi-about'
    
    tk-multi-workfiles2: '@maya.apps.tk-multi-workfiles2'

    tk-multi-publish2: '@maya.apps.tk-multi-publish2'

    tk-multi-loader2: '@maya.apps.tk-multi-loader2'

    tk-multi-shotgunpanel: '@maya.apps.tk-multi-shotgunpanel'

  location: "@common.engines.tk-maya.location"
  menu_favourites: 
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  run_at_startup:
  - {app_instance: tk-multi-shotgunpanel, name: ''}
  launch_builtin_plugins: [basic]
  automatic_context_switch: false

