# Copyright (c) 2016 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Houdini Integration when it
# is running in its project level configuration

includes:
- ../common/engines.yml
- ../common/apps.yml
- apps.yml


houdini.project:
  apps:
    tk-multi-about: '@common.apps.tk-multi-about'

    tk-multi-publish2: '@houdini.apps.tk-multi-publish2'

    tk-multi-loader2: '@houdini.apps.tk-multi-loader2'

    tk-multi-shotgunpanel: '@houdini.apps.tk-multi-shotgunpanel'

  location: "@common.engines.tk-houdini.location"
  menu_favourites: []
  run_at_startup:
  - {app_instance: tk-multi-shotgunpanel, name: ''}
  launch_builtin_plugins: [basic]
  automatic_context_switch: false

