description: Apps and Engines when launching with a site level context.

################################################################################

includes:
- ./includes/frameworks.yml
- ./includes/settings/tk-desktop.yml

################################################################################
# configuration for all engines to load in a project context

engines:
  tk-desktop: '@settings.tk-desktop.site'

################################################################################
# reference all of the common frameworks

frameworks: "@frameworks"
